# Site settings
title: Zsolti blogja
#email: spam.me.pleease@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Csak szórakozom egy sort a Jekyllel, egyelőre
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zsoltiblog.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: redcarpet
highlighter: pygments
