# Site settings
title: Zsolti blogja
description: > # this means to ignore newlines until "baseurl:"
  Csak szórakozom egy sort a Jekyllel, egyelőre
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zsoltiblog.github.io" # the base hostname & protocol for your site
github_username:  zsoltiblog

# Build settings
markdown: redcarpet
highlighter: pygments

timezone: Europe/Budapest
